### ISSUE TITLE
Google Images is considered a "shop" page

### ISSUE THREAD

**Issue by lindaicing** [CubeOfCheese/Ethicli#90]

**Comment by CubeOfCheese** [comment]
It looks like this is highly dependent on the search results
A query of "advark" is not recognized as a shopping page
But a query of "flip a coin" is because the shopword "in stock" is falsely recognized
![imagen](https://user-images.githubusercontent.com/16740469/86399144-979e4800-bc5b-11ea-90c9-e4280d2b2d22.png)

**Comment by lindaicing** [comment]
> It looks like this is highly dependent on the search results
> A query of "advark" is not recognized as a shopping page
> But a query of "flip a coin" is because the shopword "in stock" is falsely recognized
> ![imagen](https://user-images.githubusercontent.com/16740469/86399144-979e4800-bc5b-11ea-90c9-e4280d2b2d22.png)

This was resolved in the blacklist. There may always be these kinds of errors in large search engines, particularly for necessary shops that don't have too many words that identify them as shops in their code.
